name: Ig Clone Project CICD Pipeline

on:
  push:
    branches: [dev]
  pull_request:
    branches: [dev]

jobs:
  CI_and_CD:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:

      - uses: actions/checkout@v2
        with:
          ref: dev

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Set ENV file
        working-directory: ./Backend
        run: echo ${{ secrets.ENV_PORT }} >> .env 
          | echo ${{ secrets.ENV_DB_USERNAME }} >> .env 
          | echo ${{ secrets.ENV_DB_PASSWORD }} >> .env 
          | echo ${{ secrets.ENV_DB_NAME }} >> .env 
          | echo ${{ secrets.ENV_TOKEN_KEY }} >> .env



      - name: Install node modules for backend and start server
        working-directory: ./Backend
        run: |
          ls
          npm install 
          npm start &
          

      - name: Run test backend 
        working-directory: ./Backend
        run: npm test
          
          

      - name: Install node modules for frontend and run test
        working-directory: ./Frontend
        run: |
          npm install 
          npm test

      - name: Success
        if: success()
        run: echo "hello world"
      - name: Failure
        if: failure()
        run: echo "failllll"

      